### ISSUE TITLE
Request to share the model file.

### ISSUE THREAD

**Issue by ycyoon** [zeroQiaoba/AffectGPT#1]
It would be helpful if the trained model could be provided for inferring. (Perhaps the files located in video_llama/output/multimodal_llama_stage3_finetune/20230722155059_100_1000_1000 could be shared.)"

**Comment by zeroQiaoba** [comment]
Thanks very much for your interest in our work. Our code is public and you can train your own AffectGPT. Meanwhile, the performance of current systems in emotional reasoning is still limited. The main reason is that our collected dataset is too small (i.e. 100 samples). We are still working hard on this task and collecting more samples for better performance. Please wait patiently and pay attention to our follow-up work.
