### ISSUE TITLE
Request for Additional Results on AffectGPT in ‘baseline_results’

### ISSUE THREAD

**Issue by bbbdbbb** [zeroQiaoba/AffectGPT#2]
Hello,

First of all, I'd like to extend my gratitude for your work on this project. It has been incredibly insightful and valuable to the community.

I am writing to inquire if it would be possible to supplement the baseline_results with the emotional reasoning results of AffectGPT. My team and I are interested in comparing the performance of AffectGPT against other models to better understand its capabilities and strengths.

Thank you for considering this request. We look forward to any updates you might be able to share.

**Comment by bbbdbbb** [comment]
The section where you mention, "First, we randomly split the EMER dataset into 80 training samples and 20 testing samples," caught my attention.

Could you kindly provide additional details or share the specific split of the dataset used in your experiments? Having access to the exact division of training and testing samples would be incredibly beneficial for researchers like us, aiming to compare the capabilities of different models under consistent conditions.

Thanks!

**Comment by zeroQiaoba** [comment]
Thanks very much for your interest. We are expanding the original dataset and intend to include the expanded dataset as one of the tracks in the MER2024 challenge. Please pay attention to our recent work. Extended datasets and additional results are planned for release in May, 2024.

**Comment by bbbdbbb** [comment]
Thank you for your response. I wish you all the best with the upcoming MER2024 challenge. I will continue to follow it closely.
